files:
  - .mergify/config.yml
  - .browserslistrc
  - .editorconfig
  - .github/toc.yml
  - .hadolint.yaml
  - .markdownlint.json
  - .mdlrc
  - .mdlrc.rb
  - .mergify/config.yml
  - .remarkrc
  - .yamllint.yml
  - web/stylelint.config.js: stylelint.config.js
  # - web/.eslintrc.js: eslintrc.browser.js
  # - web/tslint.json: tslint.json
  # - tslint.json: tslint.json
  - .htmlhintrc
  - .htmllintrc
