version: 2.1

workflows:
  version: 2
  circleci-build:
    jobs:
      - debian: { matrix: { parameters: { base: [ debian ], tag: [ latest, stable, stable-slim ] }}}
      - debian: { matrix: { parameters: { base: [ ubuntu ], tag: [ latest, rolling, "20.04", "18.04" ] }}}

commands:
  prepare:
    steps:
      - checkout
      - run:
          name: Print env info
          command: |
            uname -a
            sw_vers || true
      - run:
          name: Update system package managers
          command: |
            if command -v apt-get >/dev/null 2>&1; then apt-get update --yes; fi
            if command -v apk >/dev/null 2>&1; then apk update --no-cache; fi
            if command -v yum >/dev/null 2>&1; then command -v dnf >/dev/null 2>&1 || yum install -y dnf; fi
  build:
    steps:
      - run: make

jobs:
  debian:
    parameters:
      base:
        type: string
      tag:
        type: string
    docker:
      - image: "<< parameters.base >>:<< parameters.tag >>"
    steps:
      - prepare
      - run: DEBIAN_FRONTEND=noninteractive apt-get install --yes build-essential curl ruby ruby-dev pandoc zlib1g zlib1g-dev imagemagick
      - run: curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt-get install --yes nodejs
      - build
