name: AutoMerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge-humans:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge 🎋 for humans 👨‍💻
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge
          MERGE_METHOD: merge
          UPDATE_LABELS: autoupdate
          UPDATE_METHOD: rebase

  automerge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge 🎋 for dependabot 🤖
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge
          MERGE_METHOD: rebase
          MERGE_FILTER_AUTHOR: dependabot[bot]
