name: Build and Test

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4

      - name: Setup nodeJS 🧩
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Setup ruby 🧩
        uses: ruby/setup-ruby@v1.65.0
        with:
          ruby-version: '2.7'

      - name: Build 🔧
        run: make bootstrap lint build
