name: AutoMerge for Dependabot

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Merge 🎋
        uses: ahmadnassri/action-dependabot-auto-merge@v2.2.0
        with:
          target: minor
          github-token: ${{ secrets.automerge-dependabot }}
